name: Daily Manga Ranking
on:
  schedule:
    - cron: '0 22 * * *'     # 07:00 JST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run script
        run: python ranking_to_notion.py
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB:    ${{ secrets.NOTION_DB }}
